# Settings for libraries used by specific SCADS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   
PKG_PATH =  
PKG_LIB =   

PKG_SYSINC =
PKG_SYSLIB =  
PKG_SYSPATH = 
