# -*- tcl -*-

  # +------------------------------------------------------------------------------------+ 
  # | This file is part of Coiled-Coil Builder.                                          | 
  # |                                                                                    | 
  # | Coiled-Coil Builder is free software: you can redistribute it and/or modify        | 
  # | it under the terms of the GNU General Public License as published by               | 
  # | the Free Software Foundation, either version 3 of the License, or                  | 
  # | (at your option) any later version.                                                | 
  # |                                                                                    | 
  # | Coiled-Coil Builder is distributed in the hope that it will be useful,             | 
  # | but WITHOUT ANY WARRANTY without even the implied warranty of                      | 
  # | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                      | 
  # | GNU General Public License for more details.                                       | 
  # |                                                                                    | 
  # | You should have received a copy of the GNU General Public License                  | 
  # | along with Coiled-Coil Builder.  If not, see <http:www.gnu.org/licenses/>.         | 
  # |                                                                                    | 
  # |  *cr                                                                               | 
  # |  *cr            (C) Copyright 1995-2013 The Board of Trustees of the               | 
  # |  *cr                        University of Pennsylvania                             | 
  # |  *cr                         All Rights Reserved                                   | 
  # |  *cr                                                                               | 
  # +------------------------------------------------------------------------------------+ 
# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded crick 1.0 [list source [file join $dir crick.tcl ]]

